<?php
/**
 * ACF Field Groups for WhoAmI Options: Experience
 *
 * @package whoami
 */

acf_add_local_field_group( array(
	'key' => 'group_663e61eebab9b',
	'title' => 'Experience',
	'fields' => array(
		array(
			'key' => 'field_663e61eec7550',
			'label' => '',
			'name' => 'jobs',
			'aria-label' => '',
			'type' => 'repeater',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'layout' => 'block',
			'pagination' => 0,
			'min' => 0,
			'max' => 0,
			'collapsed' => '',
			'button_label' => 'Add Job',
			'rows_per_page' => 20,
			'sub_fields' => array(
				array(
					'key' => 'field_663e61ef0596b',
					'label' => '',
					'name' => 'job',
					'aria-label' => '',
					'type' => 'group',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'layout' => 'block',
					'sub_fields' => array(
						array(
							'key' => 'field_663e65b0ce370',
							'label' => 'Company',
							'name' => 'company',
							'aria-label' => '',
							'type' => 'text',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'maxlength' => '',
							'placeholder' => 'Company',
							'prepend' => '',
							'append' => '',
						),
						array(
							'key' => 'field_663e6565ce36f',
							'label' => 'Title',
							'name' => 'title',
							'aria-label' => '',
							'type' => 'text',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'maxlength' => '',
							'placeholder' => 'Job Title',
							'prepend' => '',
							'append' => '',
						),
						array(
							'key' => 'field_663e65c5ce371',
							'label' => 'Dates',
							'name' => 'dates',
							'aria-label' => '',
							'type' => 'text',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'maxlength' => '',
							'placeholder' => 'Dates',
							'prepend' => '',
							'append' => '',
						),
						array(
							'key' => 'field_663e65d5ce372',
							'label' => 'Location',
							'name' => 'location',
							'aria-label' => '',
							'type' => 'text',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'maxlength' => '',
							'placeholder' => 'Location',
							'prepend' => '',
							'append' => '',
						),
						array(
							'key' => 'field_663e61ef09f89',
							'label' => '',
							'name' => 'bullets',
							'aria-label' => '',
							'type' => 'repeater',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'layout' => 'block',
							'pagination' => 0,
							'min' => 0,
							'max' => 0,
							'collapsed' => '',
							'button_label' => 'Add Bullet',
							'rows_per_page' => 20,
							'sub_fields' => array(
								array(
									'key' => 'field_663e61ef0eda9',
									'label' => '',
									'name' => 'bullet',
									'aria-label' => '',
									'type' => 'text',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'default_value' => '',
									'maxlength' => '',
									'placeholder' => 'Bullet',
									'prepend' => '•',
									'append' => '',
									'parent_repeater' => 'field_663e61ef09f89',
								),
							),
						),
					),
					'parent_repeater' => 'field_663e61eec7550',
				),
			),
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'options_page',
				'operator' => '==',
				'value' => 'whoami',
			),
		),
	),
	'menu_order' => 3,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => true,
	'description' => 'Global content for WhoAmI: Experience',
	'show_in_rest' => 1,
) );