<?php
/**
 * ACF Field Groups for WhoAmI Options: Samples
 *
 * @package whoami
 */

acf_add_local_field_group( array(
	'key' => 'group_663e78bd6b8db',
	'title' => 'Samples',
	'fields' => array(
		array(
			'key' => 'field_663e78be2aefb',
			'label' => '',
			'name' => 'samples',
			'aria-label' => '',
			'type' => 'repeater',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'layout' => 'block',
			'pagination' => 0,
			'min' => 0,
			'max' => 0,
			'collapsed' => '',
			'button_label' => 'Add Sample',
			'rows_per_page' => 20,
			'sub_fields' => array(
				array(
					'key' => 'field_663e7a32dcfda',
					'label' => 'Label',
					'name' => 'label',
					'aria-label' => '',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '35',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'maxlength' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'parent_repeater' => 'field_663e78be2aefb',
				),
				array(
					'key' => 'field_663e7a3adcfdb',
					'label' => 'Links',
					'name' => 'links',
					'aria-label' => '',
					'type' => 'group',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '65',
						'class' => '',
						'id' => '',
					),
					'layout' => 'block',
					'sub_fields' => array(
						array(
							'key' => 'field_664ba0846e4b0',
							'label' => 'Interactive',
							'name' => 'interactive',
							'aria-label' => '',
							'type' => 'url',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
						),
						array(
							'key' => 'field_664ba05c6e4af',
							'label' => 'Source',
							'name' => 'source',
							'aria-label' => '',
							'type' => 'url',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
						),
					),
					'parent_repeater' => 'field_663e78be2aefb',
				),
				array(
					'key' => 'field_663e8ea751461',
					'label' => 'Is iFrame?',
					'name' => 'is_iframe',
					'aria-label' => '',
					'type' => 'true_false',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '35',
						'class' => '',
						'id' => '',
					),
					'message' => '',
					'default_value' => 1,
					'ui_on_text' => 'iFrame',
					'ui_off_text' => 'Image',
					'ui' => 1,
					'parent_repeater' => 'field_663e78be2aefb',
				),
				array(
					'key' => 'field_663e8faf51462',
					'label' => 'iFrame Source',
					'name' => 'iframe',
					'aria-label' => '',
					'type' => 'url',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array(
						array(
							array(
								'field' => 'field_663e8ea751461',
								'operator' => '==',
								'value' => '1',
							),
						),
					),
					'wrapper' => array(
						'width' => '65',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => 'iFrame URL',
					'parent_repeater' => 'field_663e78be2aefb',
				),
				array(
					'key' => 'field_663e7a6fdcfdc',
					'label' => 'Image',
					'name' => 'image',
					'aria-label' => '',
					'type' => 'image',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array(
						array(
							array(
								'field' => 'field_663e8ea751461',
								'operator' => '!=',
								'value' => '1',
							),
						),
					),
					'wrapper' => array(
						'width' => '65',
						'class' => '',
						'id' => '',
					),
					'return_format' => 'array',
					'library' => 'all',
					'min_width' => '',
					'min_height' => '',
					'min_size' => '',
					'max_width' => '',
					'max_height' => '',
					'max_size' => '',
					'mime_types' => '',
					'preview_size' => 'medium',
					'parent_repeater' => 'field_663e78be2aefb',
				),
				array(
					'key' => 'field_663e90ebe3831',
					'label' => '',
					'name' => 'description',
					'aria-label' => '',
					'type' => 'wysiwyg',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'tabs' => 'all',
					'toolbar' => 'full',
					'media_upload' => 1,
					'delay' => 0,
					'parent_repeater' => 'field_663e78be2aefb',
				),
			),
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'options_page',
				'operator' => '==',
				'value' => 'whoami',
			),
		),
	),
	'menu_order' => 6,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => true,
	'description' => 'Global content for WhoAmI: Samples',
	'show_in_rest' => 0,
) );
